name: 'CI/CD'

on:
  workflow_dispatch: { }

  pull_request:
    branches: [ 'master' ]

  push:
    branches: [ 'master' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  config:
    runs-on: 'ubuntu-24.04'
    permissions: { }
    outputs:
      linux-runner-image: ${{ steps.constants.outputs.linux-runner-image }}
      linux-compiler: ${{ steps.constants.outputs.linux-compiler }}
      linux-conan-profile: ${{ steps.constants.outputs.linux-conan-profile }}

      macos-runner-image: ${{ steps.constants.outputs.macos-runner-image }}
      macos-compiler: ${{ steps.constants.outputs.macos-compiler }}
      macos-conan-profile: ${{ steps.constants.outputs.macos-conan-profile }}

      conan-preset: ${{ steps.constants.outputs.conan-preset }}
      action-type: ${{ steps.constants.outputs.action-type }}
    steps:
      - name: 'Define constants'
        id: 'constants'
        run: |
          CONAN_PROFILE_SUFFIX=${{ github.event_name == 'push' && 'static' || 'debug' }}
          
          echo "linux-runner-image=ubuntu-24.04" >> $GITHUB_OUTPUT
          echo "linux-compiler=llvm-21" >> $GITHUB_OUTPUT
          echo "linux-conan-profile=linux-x86_64-${CONAN_PROFILE_SUFFIX}" >> GITHUB_OUTPUT
          
          echo "macos-runner-image=macos-26" >> $GITHUB_OUTPUT
          echo "macos-compiler=apple-clang-17" >> $GITHUB_OUTPUT
          echo "macos-conan-profile=macos-arm64-${CONAN_PROFILE_SUFFIX}" >> $GITHUB_OUTPUT
          
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "conan-preset=conan-release" >> $GITHUB_OUTPUT
            echo "action-type=Release" >> $GITHUB_OUTPUT
          else
            echo "conan-preset=conan-debug" >> $GITHUB_OUTPUT
            echo "action-type=Debug" >> $GITHUB_OUTPUT
          fi

  lint-commits:
    runs-on: ${{ needs.config.outputs.linux-runner-image }}
    permissions:
      contents: 'read'
    needs: [ 'config' ]
    steps:
      - name: 'Clone the repository'
        uses: 'actions/checkout@v6'
        with:
          fetch-depth: 0

      - name: 'Setup node'
        uses: 'actions/setup-node@v6'
        with:
          node-version: lts/*

      - name: 'Install commitlint'
        run: npm install -D @commitlint/cli @commitlint/config-conventional

      - name: 'Validate commits'
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            npx commitlint --from ${{ github.event.before }} --to ${{ github.event.after }} --verbose
          else
            npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
          fi

  find-changes:
    runs-on: ${{ needs.config.outputs.linux-runner-image }}
    permissions:
      contents: 'read'
    needs: [ 'config', 'lint-commits' ]
    outputs:
      cpp-changed: ${{ steps.changes.outputs.cpp }}
      cmake-changed: ${{ steps.changes.outputs.cmake }}
    steps:
      - name: 'Clone the repository'
        uses: 'actions/checkout@v6'

      - name: 'Find changes'
        id: 'changes'
        uses: 'dorny/paths-filter@v4'
        with:
          filters: |
            cpp:
              - added|modified:
                - './**/*.cpp'
                - './**/*.cc'
                - './**/*.cppm'
                - './**/*.ixx'
                - './**/*.hpp'
                - './**/*.hxx'
                - './**/*.h'
            
            cmake:
              - added|modified:
                - './**/CMakeLists.txt'

  lint-cmake:
    runs-on: ${{ needs.config.outputs.linux-runner-image }}
    permissions:
      contents: 'read'
    needs: [ 'config', 'find-changes' ]
    if: needs.find-changes.outputs.cmake-changed == true
    steps:
      - name: 'Clone the repository'
        uses: 'actions/checkout@v6'

      - name: 'Setup cmake-lint'
        uses: 'aminya/setup-cpp@v1'
        with:
          cmake-lint: true

      - name: 'Run cmake-lint'
        run: cmake-lint -c .cmake-format.py ./**/CMakeLists.txt

  lint-cpp:
    runs-on: ${{ needs.config.outputs.linux-runner-image }}
    permissions:
      contents: 'read'
    needs: [ 'config', 'find-changes' ]
    if: needs.find-changes.outputs.cpp-changed == true
    steps:
      - name: 'Clone the repository'
        uses: 'actions/checkout@v6'

      - name: 'Setup C++ dependencies'
        uses: 'aminya/setup-cpp@v1'
        with:
          cmake: true
          compiler: ${{ needs.config.outputs.linux-compiler }}
          clang-tidy: true
          ninja: true
          conan: true

      - name: 'Install project dependencies'
        run: >
          conan install .
          --build=missing
          --profile:all=conan-profiles/${{ needs.config.outputs.linux-conan-profile }}
          -s:a build_type=${{ needs.config.outupts.action-type }}

      - name: 'Configure project'
        run: cmake --preset ${{ needs.config.outputs.conan-preset }} -D CMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: 'Lint cpp sources'
        run: run-clang-tidy -config-file .clang-tidy -p build/${{ needs.config.outputs.action-type }}

  lint-merge:
    runs-on: ${{ needs.config.outputs.linux-runner-image }}
    needs: [ 'config', 'lint-cmake', 'lint-cpp' ]
    if: |
      (needs.lint-cmake.result == 'success' || needs.lint-cmake.result == 'skipped') &&
      (needs.lint-cpp.result == 'success' || needs.lint-cpp.result == 'skipped')
    steps:
      - name: 'Output info'
        run: |
          echo "lint-cmake-trigger=${{ needs.lint-cmake.result }}"
          echo "lint-cpp-trigger=${{ needs.lint-cpp.result }}"


  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: 'read'
    needs: [ 'config', 'lint-merge' ]
    strategy:
      matrix:
        include:
          - os: ${{ needs.config.outputs.linux-runner-image }}
            compiler: ${{ needs.config.outputs.linux-compiler }}
            conan-profile: ${{ needs.config.outputs.linux-conan-profile }}
          - os: ${{ needs.config.outputs.macos-runner-image }}
            compiler: ${{ needs.config.outputs.macos-compiler }}
            conan-profile: ${{ needs.config.outputs.macos-conan-profile }}
    steps:
      - name: 'Clone the repository'
        uses: 'actions/checkout@v6'

      - name: 'Install project dependencies'
        uses: 'aminya/setup-cpp@v1'
        with:
          compiler: ${{ matrix.compiler }}
          cmake: true
          ninja: true
          conan: true

      - name: 'Install dependencies'
        run: conan install . --build=missing --profile:all=conan-profiles/${{ matrix.conan-profile }}

      - name: 'Configure project'
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            cmake --preset ${{ needs.config.outputs.conan-preset }} -D CI_CD_RELEASE=ON
          else
            cmake --preset ${{ needs.config.outputs.conan-preset }}
          fi

      - name: 'Build project'
        run: cmake --build --preset ${{ needs.config.outputs.conan-preset }}

      - name: 'Archive complete build artifacts'
        run: tar -czf build-archive-${{ github.run_id }}-${{ runner.os }}.tar.gz CMakeUserPresets.json build

      - name: 'Upload complete build archive'
        uses: 'actions/upload-artifact@v4'
        with:
          name: build-archive-${{ github.run_id }}-${{ runner.os }}
          path: build-archive-${{ runner.os }}.tar.gz
          retention-days: 1
          overwrite: true

      - name: 'Find conan directory'
        id: 'conan-config'
        run: echo "CONAN_CONFIG_HOME=$(conan config home)" >> $GITHUB_ENV

      - name: 'Cache conan directories'
        uses: 'actions/cache@v5'
        with:
          path: ${{ env.CONAN_CONFIG_HOME }}
          key: conan-${{ runner.os }}-${{ github.run_id }}

  test:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: 'read'
    needs: [ 'config', 'build' ]
    strategy:
      matrix:
        include:
          - os: ${{ needs.config.outputs.linux-runner-image }}
            compiler: ${{ needs.config.outputs.linux-compiler }}
          - os: ${{ needs.config.outputs.macos-runner-image }}
            compiler: ${{ needs.config.outputs.macos-compiler }}
    steps:
      - name: 'Clone the repository'
        uses: 'actions/checkout@v6'

      - name: 'Setup C++ dependencies'
        uses: 'aminya/setup-cpp@v1'
        with:
          compiler: ${{ matrix.compiler }}
          cmake: true
          conan: true

      - name: 'Find conan directory'
        run: echo "CONAN_CONFIG_HOME=$(conan config home)" >> $GITHUB_ENV

      - name: 'Restore conan directories'
        uses: 'actions/cache/restore@v5'
        with:
          path: ${{ env.CONAN_CONFIG_HOME }}
          key: conan-${{ runner.os }}-${{ github.run_id }}

      - name: 'Download build artifacts'
        uses: 'actions/download-artifact@v4'
        with:
          name: build-archive-${{ github.run_id }}-${{ runner.os }}

      - name: 'Unarchive build artifacts'
        run: tar -xzf build-archive-${{ runner.os }}.tar.gz

      - name: 'Run tests'
        run: ctest --preset ${{ needs.config.outputs.conan-preset }}

  archive:
    runs-on: ${{ needs.config.outputs.linux-runner-image }}
    permissions: { }
    needs: [ 'config', 'test' ]
    if: github.event_name == 'push'
    steps:
      - name: 'Download Linux build artifacts'
        uses: 'actions/download-artifact@v4'
        with:
          path: artifacts
          pattern: build-archive-${{ github.run_id }}-*

      - name: 'Prepare Linux assets'
        run: |
          mkdir -p Linux
          tar -xzf artifacts/build-archive-${{ github.run_id }}-Linux/build-archive-*.tar.gz -C Linux
          tar -czf linux-x86_64.tar.gz -C Linux/build/${{ needs.config.outputs.action-type}}/bin .

      - name: 'Prepare macOS assets'
        run: |
          mkdir -p macOS
          tar -xzf artifacts/build-archive-${{ github.run_id }}-macOS/build-archive-*.tar.gz -C macOS
          tar -czf macos-arm64.tar.gz -C macOS/build/${{ needs.config.outputs.action-type }}/bin .

      - name: 'Upload release artifacts'
        uses: 'actions/upload-artifact@v4'
        with:
          name: release-assets-${{ github.run_id }}
          path: ./*.tar.gz

  release:
    runs-on: ${{ needs.config.outputs.linux-runner-image }}
    permissions:
      contents: 'write'
    needs: [ 'config', 'archive' ]
    steps:
      - name: 'Clone the repository'
        uses: 'actions/checkout@v6'
        with:
          fetch-depth: 0

      - name: 'Bump version and push tag'
        id: 'bump-version'
        uses: 'mathieudutour/github-tag-action@v6.2'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Download archived release executables'
        uses: 'actions/download-artifact@v4'
        with:
          name: release-assets-${{ github.run_id }}

      - name: 'Create GitHub release'
        uses: 'ncipollo/release-action@v1'
        with:
          tag: ${{ steps.bump-version.outputs.new_tag }}
          name: Release ${{ steps.bump-version.outputs.new_tag }}
          body: ${{ steps.bump-version.outputs.changelog }}
          artifacts: ./*.tar.gz
